inventory_python/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    # ex: /inventory/
    path('', views.index, name='index'),
    # ex: /inventory/5/
    path('<int:id>/', views.detail, name='detail'),

]

inventory_python/inventory_python/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    # REST API
    path('api/items/', views.product_collection, name='product_collection'),
]

inventory_python/inventory/models.py
from django.db import models
from rest_framework import serializers

# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=100)
    number_in_stock = models.IntegerField(default=0)
    product_price = models.IntegerField(default=0)

class ItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = Product
        fields = ('product_name', 'number_in_stock', 'product_price')

inventory_python/inventory/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from .models import Product, ItemSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

# Create your views here.


def index(request):
    product_list = Product.objects.order_by('product_name')
    context = {'product_list': product_list}
    return render(request, 'inventory/index.html', context)

def detail(request, id):
    try:
        product = Product.objects.get(pk=id)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")
    return render(request, 'inventory/detail.html', {'product': product})


@api_view(['GET'])
def product_collection(request):
    if request.method == 'GET':
        item = Product.objects.all()
        serializer = ItemSerializer(item, many=True)
        return Response(serializer.data)

inventory_python/inventory/templates/inventory/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{product.product_name}}</title>
  </head>
  <body>
    <p>Product Name: {{ product.product_name }}</p>
    <p>In Stock: {{ product.number_in_stock }}</p>
    <p>Unit Price: {{ product.product_price }}</p>    
  </body>
</html>

inventory_python/inventory/templates/inventory/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Inventory</title>
  </head>
  <body>
    
    {% if product_list %}
        <ul>
        {% for product in product_list %}
            <li><a href="{% url 'inventory:detail' product.id %}">{{ product.product_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No product is available.</p>
    {% endif %}

  </body>
</html>